- name: Patch Each Secret
  kubernetes.core.k8s_json_patch:
    verify_ssl: false
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: "{{ gitops_namespace }}"
    kind: Secret
    name: "{{ secret_to_patch[secret_index | int].metadata.name }}"
    patch:
      - op: add
        path: /data/shard
        value: "{{ shard | string | b64encode }}"

- name: Print Secret Number
  debug:
    msg: "Patched Secret Number {{ secret_index }}"

- name: Increment Secret Index
  set_fact:
    secret_index: "{{ secret_index | int + 1 }}"
  when: "secret_index | int < secret_to_patch | length -1"
